name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./...

      - name: Run tests and generate coverage report
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.out
          threshold: 80
          local-prefix: github.com/travis-james/go-downloader
          fail-coverage: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out
          if-no-files-found: error